DB:
  type: mysql
  host: localhost
  name: root
  password: wyw123456
  database: kping_custom_test
  synchronize: false
  port: 3306

REDIS:
  host: localhost
  port: 6379
  password: wyw123456
  db: 0

LOG:
  on: true
  level: info

ALI_CLOUD:
  endpoint: ''
  apiVersion: ''

SECRET: ArcticRug25
